var firstListItem = document.querySelector("ul li");
//console.log(firstListItem);
firstListItem.style.textTransform = "uppercase";
var moreReasons = document.querySelector(".more-reasons");
//console.log(moreReasons);
moreReasons.style.fontSize = "2.5em";
var whyJS = document.querySelector("h3");
//console.log(whyJS);
whyJS.innerHTML = "<span class='highlight'>Javascript</span>";
//console.log(whyJS);
var highlight = document.querySelector(".highlight");
highlight.style.backgroundColor = "#ffff82";
var mainImage = document.querySelector("img");
console.log(mainImage);
mainImage.src = "img/js-code.png";
mainImage.alt = "Javascript code example";
